### ISSUE TITLE
The server is down

### ISSUE THREAD

**Issue by edlaurence** [Royal-Rebels/Royal-Rebels#148]
As of 11:38 AM Pacific  :-)

**Comment by triarry** [comment]
Fixed! We're in contact with the host about this issue of it not going back
up on its own.


On Wed, Jun 17, 2015 at 2:46 PM, edlaurence <notifications@github.com>
wrote:

> As of 11:38 AM Pacific :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Royal-Rebels/Royal-Rebels/issues/148>.
>



-- 
*Nicholas Plante*
Bachelors Student | Computer Science
The College of Engineering
Drexel University 2016
nicholas.r.plante@drexel.edu

**Comment by edlaurence** [comment]
WOW

**Comment by edlaurence** [comment]
You just made my afternoon much less productive! Thanks!

**Comment by triarry** [comment]
Haha no worries!

On Wed, Jun 17, 2015 at 2:50 PM, edlaurence <notifications@github.com>
wrote:

> You just made my afternoon much less productive! Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Royal-Rebels/Royal-Rebels/issues/148#issuecomment-112912234>
> .
>



-- 
*Nicholas Plante*
Bachelors Student | Computer Science
The College of Engineering
Drexel University 2016
nicholas.r.plante@drexel.edu

**Comment by edlaurence** [comment]
Except I'm still not connecting. Does it take a few minutes?

**Comment by triarry** [comment]
Oops - going up now. Good thing you let me know, my internet was partially disconnected.

**Comment by triarry** [comment]
Up now.
